language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-basic-project' ]; then cd .. && eval "mv $currentfolder generator-basic-project" && cd generator-basic-project; fi

